import Shell from "../components/Shell";
import { C } from "../lib/colors";

export default function PrivacyPage() {
  return (
    <Shell>
      <section style={{ padding: "40px 28px", maxWidth: 820, margin: "0 auto" }}>
        <div className="fu">
          <h2 style={{ fontFamily: "'Fraunces', serif", fontSize: 26, fontWeight: 500, color: C.forest, marginBottom: 4 }}>
            Privacy & Policies
          </h2>
          <p style={{ fontSize: 14, color: C.textLight, marginBottom: 28 }}>
            Information about how this site operates and how you can use its content.
          </p>
        </div>

        {/* Privacy Policy Section */}
        <div className="fu" style={{ animationDelay: "0.06s", marginBottom: 32, padding: 28, background: C.card, border: `1px solid ${C.borderSoft}`, borderRadius: 14, boxShadow: C.shadow }}>
          <h3 style={{ fontFamily: "'Fraunces', serif", fontSize: 18, fontWeight: 500, color: C.forest, marginBottom: 16 }}>
            Privacy Policy
          </h3>
          <div style={{ fontSize: 14, color: C.textMid, lineHeight: 1.7 }}>
            <p style={{ marginBottom: 14 }}>
              <strong style={{ color: C.forest }}>Data Collection:</strong> This website does not collect, store, or transmit any personal data. We do not use cookies, analytics, or tracking software to monitor your activity.
            </p>
            <p style={{ marginBottom: 14 }}>
              <strong style={{ color: C.forest }}>Local Storage:</strong> The site may use your browser's local storage for convenience features (e.g., saving your progress within a session). This data remains only on your device and is never sent to our servers.
            </p>
            <p>
              <strong style={{ color: C.forest }}>Third-Party Services:</strong> External links on this site (e.g., College Board, GitHub) are subject to their respective privacy policies.
            </p>
          </div>
        </div>

        {/* Terms of Use Section */}
        <div className="fu" style={{ animationDelay: "0.12s", marginBottom: 32, padding: 28, background: C.card, border: `1px solid ${C.borderSoft}`, borderRadius: 14, boxShadow: C.shadow }}>
          <h3 style={{ fontFamily: "'Fraunces', serif", fontSize: 18, fontWeight: 500, color: C.forest, marginBottom: 16 }}>
            Terms of Use
          </h3>
          <div style={{ fontSize: 14, color: C.textMid, lineHeight: 1.7 }}>
            <p style={{ marginBottom: 14 }}>
              <strong style={{ color: C.forest }}>Content Freedom:</strong> You are free to use, share, modify, and redistribute any content on this website however you see fit. There are no terms of service governing your use.
            </p>
            <p style={{ marginBottom: 14 }}>
              <strong style={{ color: C.forest }}>No Liability:</strong> This site is provided as-is without warranties. We are not responsible for any consequences of your use of this site or its content.
            </p>
            <p>
              <strong style={{ color: C.forest }}>Personal Responsibility:</strong> Users are expected to use this site responsibly and in accordance with applicable laws and academic integrity policies.
            </p>
          </div>
        </div>

        {/* Content Disclaimer Section */}
        <div className="fu" style={{ animationDelay: "0.18s", padding: 28, background: C.card, border: `1px solid ${C.borderSoft}`, borderRadius: 14, boxShadow: C.shadow }}>
          <h3 style={{ fontFamily: "'Fraunces', serif", fontSize: 18, fontWeight: 500, color: C.forest, marginBottom: 16 }}>
            Content Disclaimer
          </h3>
          <div style={{ fontSize: 14, color: C.textMid, lineHeight: 1.7 }}>
            <p style={{ marginBottom: 14 }}>
              <strong style={{ color: C.forest }}>Not Official:</strong> This website is an independent educational resource. It is not affiliated with, endorsed by, or approved by the College Board. AP® is a registered trademark of the College Board.
            </p>
            <p style={{ marginBottom: 14 }}>
              <strong style={{ color: C.forest }}>Content Source:</strong> Course information and exam details are sourced from publicly available College Board materials. All study guides, summaries, and explanations are written and edited by humans, not generated by AI.
            </p>
            <p style={{ marginBottom: 14 }}>
              <strong style={{ color: C.forest }}>Score Predictor Accuracy:</strong> The AP Score Predictor provides rough estimates based on historical College Board exam data. Actual cutoffs vary annually and are not released until after the exam administration. Predictions are approximate and should not be relied upon as definitive. Students near score boundaries should treat predictions with a ±5-10% margin of error.
            </p>
            <p>
              <strong style={{ color: C.forest }}>Educational Use:</strong> This site is intended purely for educational purposes to help students prepare for AP exams. Check your school's academic integrity policies regarding use of external study resources.
            </p>
          </div>
        </div>

        {/* Open Source Section */}
        <div className="fu" style={{ animationDelay: "0.24s", marginTop: 32, padding: 28, background: C.card, border: `1px solid ${C.borderSoft}`, borderRadius: 14, boxShadow: C.shadow }}>
          <h3 style={{ fontFamily: "'Fraunces', serif", fontSize: 18, fontWeight: 500, color: C.forest, marginBottom: 16 }}>
            Open Source
          </h3>
          <div style={{ fontSize: 14, color: C.textMid, lineHeight: 1.7 }}>
            <p>
              This entire website is completely open source. You can view, use, modify, and contribute to the source code on <a href="https://github.com/ImBored7820/MS-AP" target="_blank" rel="noopener noreferrer" style={{ color: C.sage, textDecoration: "underline", fontWeight: 500 }}>GitHub</a>. We welcome community contributions, bug reports, and improvements.
            </p>
          </div>
        </div>
      </section>
    </Shell>
  );
}
